apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-combined-app-staging
  namespace: argo
  finalizers:
    - resources-finalizer.argo.argoproj.io
spec:
  project: staging
  source:
    path: kustomize/overlays/staging
    repoURL: https://github.com/ammarwa/argo-combined-app
    targetRevision: HEAD
    kustomize:
      images:
      - vfarcic/devops-toolkit-series:3.0.0
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
