---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production
  namespace: argo
  finalizers:
    - resources-finalizer.argo.argoproj.io
spec:
  project: production
  source:
    repoURL: https://github.com/ammarwa/argo-combined-demo.git
    targetRevision: HEAD
    path: production
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging
  namespace: argo
  finalizers:
    - resources-finalizer.argo.argoproj.io
spec:
  project: staging
  source:
    repoURL: https://github.com/ammarwa/argo-combined-demo.git
    targetRevision: HEAD
    path: staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true

