apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argo
  finalizers:
    - resources-finalizer.argo.argoproj.io
spec:
  project: production
  source:
    path: argo-workflows/overlays/production
    repoURL: https://github.com/ammarwa/argo-combined-demo
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: false
      prune: false

